### PR TITLE
tests + babel on 0.10 and 0.12

### PR DESCRIPTION
**Pull request by ralphtheninja**
Closes https://github.com/ralphtheninja/pgdown/issues/10

### CODE REVIEW

**Comment by deanlandolt** [comment]
<3

**Comment by ralphtheninja** [comment]
The tests should pass fine. Holding off with merge until `README` has been updated.

**Comment by ralphtheninja** [comment]
@juliangruber Can I get a +1? :)

**Comment by juliangruber** [comment]
...+1 :D

**Pull request merged**
