### PR TITLE
add usage to readme

### PR DESCRIPTION
**Pull request by ralphtheninja**

### CODE REVIEW

**Comment by ralphtheninja** [comment]
@juliangruber Let me know if you have any input on this. Going to merge quick in the beginning.

**Comment by juliangruber** [comment]
do you _need_ to specify those encodings when initializing the db? or does it work with any

**Comment by deanlandolt** [comment]
It _will_ work w/ any soonish. We just need to sniff the `valueEncoding` and map to postgres types -- or allow it to be specified explicitly on the `valueEncoding` object.

In fact, since we're not using any of the `jsonb` we could just change it to `text` and it would Just Work w/ any string, not only JSON (it's storing the json as `jsonb` mostly to verify all this works). Though to store arbitrary buffers efficiently we'll need to use something like `bytea`, or change the encoding on the column to something like node's `binary` string encoding (ascii8). Once we get that worked out we could prob just do this by default, and allow `text` columns to be opted into (e.g. by setting `keyEncoding` or `valueEncoding` to `utf-8`).

**Comment by juliangruber** [comment]
ah, so this is another case where levelup needs to stay out of the encoding logic, as the backend will handle this. correct?

for this to work users will have to pass a specific encoding that won't alter values. see https://github.com/Level/abstract-leveldown/blob/master/abstract-leveldown.js#L116

If having native support for this "stay out of my encoding"-encoding in levelup sounds like a good thing to have, I can make a pull request to add that.

**Comment by deanlandolt** [comment]
A "stay out of my way" encoding config would be a _very_ good thing to have! I was just bitching about this to @ralphtheninja last night!

:+1:

**Comment by ralphtheninja** [comment]
`process.browser = true` :grinning:

**Comment by juliangruber** [comment]
+1 this :) https://github.com/Level/abstract-leveldown/pull/85

**Comment by ralphtheninja** [comment]
Oh yeah, sorry, forgot.

**Pull request merged**
